tasks:
# - task: unconditional
#   sample_length: 300
#   num_samples: 10
- task: unconditional
  sample_length: 60
  num_samples: 20
- task: unconditional
  sample_length: 80
  num_samples: 20
# - task: unconditional
#   sample_length: 100
#   num_samples: 5
