# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=5 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase1.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/motif_scaffolding_model/lightning_logs/version_0/checkpoints/epoch\=3278-step\=780000.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_0" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=5 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase1.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_0/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_1" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=5 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase1.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_1/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_2" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=5 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase1.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_2/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_3" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=5 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase1.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_3/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_4" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \
#
# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=5 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase1.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_4/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_5" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=5 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase1.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_5/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_6" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=5 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase1.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_6/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_7" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=3 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase2.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase1_7/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_0" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     experiment.lightning.accumulate_grad_batches=2
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=3 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase2.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_0/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_1" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     experiment.lightning.accumulate_grad_batches=2
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=3 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase2.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_1/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_2" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     experiment.lightning.accumulate_grad_batches=2
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=3 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase2.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_2/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_3" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     experiment.lightning.accumulate_grad_batches=2
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=3 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase2.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_3/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_4" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     experiment.lightning.accumulate_grad_batches=2
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

# bash submit_train_generic.sh 16 2 \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=3 \
#     datamodule.num_workers=4 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=false \
#     model.num_blocks=12 \
#     model.num_attn_pair_bias_heads=4 \
#     model.add_same_chain_feature=true \
#     model.disable_absolute_res_idx=true \
#     model.embed_hotspot_type=true \
#     model.embed_token_is_copy_mask=true \
#     model.embed_rigids_noising_mask=true \
#     model.patch_unit_vec_bug=true \
#     model.use_entity_id_unmasking=true \
#     lmodule.use_ema=true \
#     corrupter.prealign_noise=false \
#     corrupter.use_uniform_rot_noise=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=false \
#     corrupter.center_on_noised=false \
#     corrupter.center_on_motif_then_hotspots=true \
#     corrupter.sig_perturb=2 \
#     lmodule.use_interchain_fafe_loss=true \
#     dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase2.yaml \
#     experiment.lightning.devices=8 \
#     experiment.lightning.num_nodes=2 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=20000 \
#     experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_4/lightning_logs/version_0/checkpoints/last.ckpt" \
#     hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_5" \
#     lmodule.use_brownian_rot_path_loss=true \
#     corrupter.rots_use_brownian_path=true \
#     experiment.lightning.accumulate_grad_batches=2
#     # lmodule.strict_weight_loading=false \
#     # experiment.lightning.gradient_clip_val=5 \

bash submit_train_generic.sh 16 2 \
    domain=protein \
    paradigm=multiframefm \
    datamodule.batch_size=3 \
    datamodule.num_workers=4 \
    model.c_s=768 \
    model.c_cond=768 \
    model.c_frame=256 \
    model.c_framepair=64 \
    model.z_broadcast=true \
    model.rigid_transformer_num_blocks=1 \
    model.rigid_transformer_rigid_updates=true \
    model.use_embedder_sc_rigid_transformer=true \
    model.use_ipa_gating=true \
    model.use_qk_norm=true \
    model.use_amp=true \
    model.rot_preconditioning=false \
    model.num_blocks=12 \
    model.num_attn_pair_bias_heads=4 \
    model.add_same_chain_feature=true \
    model.disable_absolute_res_idx=true \
    model.embed_hotspot_type=true \
    model.embed_token_is_copy_mask=true \
    model.embed_rigids_noising_mask=true \
    model.patch_unit_vec_bug=true \
    model.use_entity_id_unmasking=true \
    lmodule.use_ema=true \
    corrupter.prealign_noise=false \
    corrupter.use_uniform_rot_noise=true \
    corrupter.use_stochastic_centering=true \
    corrupter.center_on_motif=false \
    corrupter.center_on_noised=false \
    corrupter.center_on_motif_then_hotspots=true \
    corrupter.sig_perturb=2 \
    lmodule.use_interchain_fafe_loss=true \
    dataset.config=/home/remote/ali16/projects/proteinzen-internal/configs/train/data/teddymer_rcsb_binding_and_motif_crop384_phase2.yaml \
    experiment.lightning.devices=8 \
    experiment.lightning.num_nodes=2 \
    experiment.lightning.strategy=ddp_find_unused_parameters_true \
    experiment.checkpointer.train_time_interval=null \
    experiment.checkpointer.every_n_train_steps=20000 \
    experiment.warm_start="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_5/lightning_logs/version_0/checkpoints/last.ckpt" \
    hydra.run.dir="/mnt/scratch/user/ali16/proteinzen_training/outputs/v1/finetune/binder_design_phase2_6" \
    lmodule.use_brownian_rot_path_loss=true \
    corrupter.rots_use_brownian_path=true \
    experiment.lightning.accumulate_grad_batches=2
    # lmodule.strict_weight_loading=false \
    # experiment.lightning.gradient_clip_val=5 \
