tasks:
- task: unconditional
  sample_length: 10
  num_samples: 10
- task: unconditional
  sample_length: 15
  num_samples: 10
- task: unconditional
  sample_length: 20
  num_samples: 10
- task: unconditional
  sample_length: 25
  num_samples: 10
- task: unconditional
  sample_length: 30
  num_samples: 10
- task: unconditional
  sample_length: 35
  num_samples: 10
- task: unconditional
  sample_length: 40
  num_samples: 10
- task: unconditional
  sample_length: 45
  num_samples: 10
- task: unconditional
  sample_length: 50
  num_samples: 10
- task: unconditional
  sample_length: 55
  num_samples: 10
- task: unconditional
  sample_length: 60
  num_samples: 10
- task: unconditional
  sample_length: 65
  num_samples: 10
- task: unconditional
  sample_length: 70
  num_samples: 10