python train.py \
    domain=protein \
    paradigm=multiframefm \
    datamodule.batch_size=24 \
    datamodule.num_workers=8 \
    model.c_s=256 \
    model.c_cond=256 \
    model.c_frame=256 \
    model.c_framepair=64 \
    model.z_broadcast=true \
    model.rigid_transformer_num_blocks=1 \
    model.rigid_transformer_rigid_updates=true \
    model.use_embedder_sc_rigid_transformer=true \
    model.use_ipa_gating=true \
    model.use_qk_norm=true \
    model.use_amp=true \
    model.rot_preconditioning=true \
    model.num_blocks=8 \
    lmodule.use_ema=true \
    corrupter.use_stochastic_centering=false \
    corrupter.center_on_motif=false \
    dataset.config=/datastor1/dy4652/proteinzen/configs/train/data/geom_conformer.yaml \
    dataset.val_config=/datastor1/dy4652/proteinzen/configs/train/data/geom_conformer_val.yaml \
    experiment.lightning.devices=4 \
    experiment.lightning.strategy=ddp_find_unused_parameters_true \
    experiment.checkpointer.train_time_interval=null \
    experiment.checkpointer.every_n_train_steps=5000 \
    hydra.run.dir="/datastor1/dy4652/proteinzen/outputs/geom_identityRot_256_conformer/train" \
    corrupter.use_uniform_rot_noise=false
# python train.py \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=8 \
#     datamodule.num_workers=8 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=true \
#     model.num_blocks=12 \
#     lmodule.use_ema=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=true \
#     corrupter.sig_perturb=4 \
#     dataset.config=/datastor1/dy4652/proteinzen/configs/train/data/geom.yaml \
#     experiment.lightning.devices=4 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=2000 \
#     hydra.run.dir="./outputs/geom_identityRot_frame/train"