dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
source $dir/env_vars.sh 

python ${REPO_ROOT}/train.py \
    domain=protein \
    paradigm=multiframefm \
    datamodule.batch_size=20 \
    datamodule.num_workers=8 \
    model.c_s=256 \
    model.c_cond=256 \
    model.c_frame=256 \
    model.c_framepair=64 \
    model.z_broadcast=true \
    model.rigid_transformer_num_blocks=1 \
    model.rigid_transformer_rigid_updates=true \
    model.use_embedder_sc_rigid_transformer=true \
    model.use_ipa_gating=true \
    model.use_qk_norm=true \
    model.use_amp=true \
    model.rot_preconditioning=true \
    model.num_blocks=8 \
    lmodule.use_ema=true \
    lmodule.strict_weight_loading=false \
    corrupter.use_stochastic_centering=false \
    corrupter.center_on_motif=false \
    corrupter.trans_prior_std=3 \
    dataset.config="'${REPO_ROOT}/configs/train/data/geom_conformer_scaffold.yaml'" \
    +dataset.val_config="'${REPO_ROOT}/configs/train/data/geom_conformer_val.yaml'" \
    experiment.lightning.devices=8 \
    experiment.lightning.strategy=ddp_find_unused_parameters_true \
    experiment.checkpointer.train_time_interval=null \
    experiment.checkpointer.every_n_train_steps=500 \
    hydra.run.dir="'${REPO_ROOT}/outputs/geom_identityRot_256_conformer_3std_stereo_hydrogen_molscaffold_IdentityNoise/train'" \
    experiment.lightning.max_epochs=-1 \
    model.use_bond_rotation=false \
    experiment.lightning.accumulate_grad_batches=2 \
    lmodule.bond_rotation_head_only=false \
    lmodule.scale_bond_length_loss=false \
    lmodule.scale_bond_angle_loss=false \
    lmodule.scale_ring_planarity_loss=false \
    dataset.include_h=true \
    model.patch_unit_vec_bug=true \
    lmodule.identity_rot_noise=true \
    lmodule.use_rot_vf_loss=false \
# python train.py \
#     domain=protein \
#     paradigm=multiframefm \
#     datamodule.batch_size=8 \
#     datamodule.num_workers=8 \
#     model.c_s=768 \
#     model.c_cond=768 \
#     model.c_frame=256 \
#     model.c_framepair=64 \
#     model.z_broadcast=true \
#     model.rigid_transformer_num_blocks=1 \
#     model.rigid_transformer_rigid_updates=true \
#     model.use_embedder_sc_rigid_transformer=true \
#     model.use_ipa_gating=true \
#     model.use_qk_norm=true \
#     model.use_amp=true \
#     model.rot_preconditioning=true \
#     model.num_blocks=12 \
#     lmodule.use_ema=true \
#     corrupter.use_stochastic_centering=true \
#     corrupter.center_on_motif=true \
#     corrupter.sig_perturb=4 \
#     dataset.config=/datastor1/dy4652/proteinzen/configs/train/data/geom.yaml \
#     experiment.lightning.devices=4 \
#     experiment.lightning.strategy=ddp_find_unused_parameters_true \
#     experiment.checkpointer.train_time_interval=null \
#     experiment.checkpointer.every_n_train_steps=2000 \
#     hydra.run.dir="./outputs/geom_identityRot_frame/train"