task_sampler:
  _target_: proteinzen.runtime.training.task.TaskSampler
  task_list:
    - _target_: proteinzen.runtime.training.motif_scaffold_v2.MixedMotifScaffoldingV2
      prob: 1.0
      t_sched: lognorm
      mode: mixed
      lognorm_mu: 0.0
      lognorm_sig: 1.0
      beta_p1: 1.9
      beta_p2: 1.0
      shift_time_scale: false
      t_min: 0.01
      t_max: 0.99
      max_frac_res: 0.5
      max_num_res: 20
      p_is_unindexed: 0.8
      name_override: motif_scaffold_unindexed